### ISSUE TITLE
Argument misunderstanding

### ISSUE THREAD

**Issue by DeepakLabh** [guettli/panorama#3]
Hi,

I wanted to know what is **file_containing_jpg_files** .

`create-panorama-from-jpg-files-in-directory file_containing_jpg_files`

I tried 
`create-panorama-from-jpg-files-in-directory data`

all the images are located in data
got the following error:
```
Traceback (most recent call last):
  File "/home/arya/deepak/venvs/panorama/bin/create-panorama-from-jpg-files-in-directory", line 11, in <module>
    sys.exit(main())
  File "/home/arya/deepak/venvs/panorama/local/lib/python2.7/site-packages/panorama/panorama.py", line 21, in main
    do_panoramas_in_dirs(args.directories)
  File "/home/arya/deepak/venvs/panorama/local/lib/python2.7/site-packages/panorama/panorama.py", line 29, in do_panoramas_in_dirs
    panorama.create_panorama_jpg_from_source_files()
  File "/home/arya/deepak/venvs/panorama/local/lib/python2.7/site-packages/panorama/panorama.py", line 139, in create_panorama_jpg_from_source_files
    self.create_pto()
  File "/home/arya/deepak/venvs/panorama/local/lib/python2.7/site-packages/panorama/panorama.py", line 119, in create_pto
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Thanks

**Comment by guettli** [comment]
thank you for reporting this. Did you find a solution?

**Comment by madmaddi** [comment]
have exactly the same problem

**Comment by guettli** [comment]
@madmaddi thank you for using my script. Could you please try to debug what is going on here? Please tell me if you need help. Do you have some knowledge of the programming language python?
